blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/line-zero/.github/security/policy
    about: Please report security vulnerabilities privately when possible.
